//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCStatikCV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aracbilgi
    {
        public int Id { get; set; }
        public string Marka { get; set; }
        public string Seri { get; set; }
        public string Model { get; set; }
        public Nullable<int> Yil { get; set; }
        public string Yakit { get; set; }
        public string Vites { get; set; }
        public string KasaTipi { get; set; }
        public string MotorGucu { get; set; }
        public string MotorHacmi { get; set; }
        public string Cekis { get; set; }
        public string Renk { get; set; }
        public string Plaka { get; set; }
        public string Takas { get; set; }
        public Nullable<int> KM { get; set; }
        public string foto1 { get; set; }
        public string foto2 { get; set; }
        public string foto3 { get; set; }
        public string foto4 { get; set; }
        public string foto5 { get; set; }
        public string Acıklama { get; set; }
    }
}
